runtime: nodejs10
service: artbymente
env_variables:
  CONTENTFUL_SPACE: $CONTENTFUL_SPACE
  CONTENTFUL_ACCESS_TOKEN: $CONTENTFUL_ACCESS_TOKEN
  MAILGUN_KEY: $MAILGUN_KEY
  MAILGUN_DOMAIN: $MAILGUN_DOMAIN
  MAILGUN_LIST: $MAILGUN_LIST
  CONTACT_EMAIL: $CONTACT_EMAIL
