name: Deploy to App Engine

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Update app.yaml
        uses: ikuanyshbekov/app-yaml-env-compiler@v1.0
        env:
          CONTENTFUL_SPACE: ${{ secrets.CONTENTFUL_SPACE }}
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
          MAILGUN_KEY: ${{ secrets.MAILGUN_KEY }}
          MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
          MAILGUN_LIST: ${{ secrets.MAILGUN_LIST }}
          CONTACT_EMAIL: ${{ secrets.CONTACT_EMAIL }}
      - name: Deploy to App Engine
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
        with:
          args: app deploy app.yaml
